//SCHEDULE ACTIONS
export const GET_SCHEDULE = 'GET_SCHEDULE';
export const CREATE_SCHEDULE = 'CREATE_SCHEDULE';
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
export const SCHEDULE_ERROR = 'SCHEDULE_ERROR';
export const ADD_EVENT = 'ADD_EVENT';
export const CLEAR_SCHEDULE = 'CLEAR_SCHEDULE';

//REGISTER ACTIONS
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

//USER VALIDATION
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

//USER MUTATION ACTIONS
export const USER_ERROR = 'USER_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const USER_DELETED = 'USER_DELETED';

//LOGIN VALIDATION
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//LOGOUT ACTION
export const LOGOUT = 'LOGOUT';

//ALERT ACTIONS
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REMOVE_CURRENT_ALERT = 'REMOVE_CURRENT_ALERT';

//GENERAL POST ACTIONS
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const CLEAR_POSTS = 'CLEAR_POSTS';

//POST LIKES & COMMENTS ACTIONS
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';

//POLL ACTIONS
export const CREATE_POLL = 'CREATE_POLL';
export const GET_POLLS = 'GET_POLLS';
export const GET_POLL = 'GET_POLL';
export const UPDATE_VOTE = 'UPDATE_VOTE';
export const UPDATE_CHOICE = 'UPDATE_CHOICE';
export const UPDATE_POLL_NAME = 'UPDATE_POLL_NAME';
export const POLL_ERROR = 'POLL_ERROR';
export const DELETE_POLL = 'DELETE_POLL';
export const CLEAR_POLLS = 'CLEAR_POLLS';
