//SCHEDULE ACTIONS
export const GET_SCHEDULE = "GET_SCHEDULE";
export const UPDATE_NAME = "UPDATE_NAME";
export const ADD_EVENT = "ADD_EVENT";

//REGISTER ACTIONS
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//USER VALIDATION
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

//LOGIN VALIDATION
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

//LOGOUT ACTION
export const LOGOUT = "LOGOUT";
export const CLEAR_USER = "CLEAR_USER";
