//SCHEDULE ACTIONS
export const GET_SCHEDULE = "GET_SCHEDULE";
export const CREATE_SCHEDULE = "CREATE_SCHEDULE";
export const UPDATE_SCHEDULE = "UPDATE_SCHEDULE";
export const SCHEDULE_ERROR = "SCHEDULE_ERROR";
export const ADD_EVENT = "ADD_EVENT";
export const CLEAR_SCHEDULE = "CLEAR_SCHEDULE";

// Generalize individual schedule updates into 'UPDATE_SCHEDULE'

//REGISTER ACTIONS
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//USER VALIDATION
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const USER_ERROR = "USER_ERROR";
export const UPDATE_USER = "UPDATE_USER";
export const USER_DELETED = "USER_DELETED";

//LOGIN VALIDATION
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

//LOGOUT ACTION
export const LOGOUT = "LOGOUT";

//ALERT ACTIONS
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
